#! /bin/sh

# Copyright 1999 Gambro BCT
#
# FILENAME: create_install
# $Header: //Bctquad3/HOME/BCT_Development/Install/Trima_v5/rcs/create_install 1.1 2001/08/17 15:34:11 ms10234 Exp ms10234 $
# PURPOSE: builds trima product within a sandbox
# CHANGELOG:
# $Log: create_install $
# Revision 1.1  2001/08/17 15:34:11  ms10234
# Initial revision

#
#
#
#
#######################################################################################
#                                                                                     #
#   use ifdef option                                                                  #
#                                                                                     #
#######################################################################################
#
#ifdef __USAGE
#
#usage:
#%C
#
#endif


echo create_install beginning at $(date)

#
#   capture current executable name for display
#

current_executable=${0##*/}


#
#   if user starts the build in the released for testing location (i.e. /releases ) set
#   the 'build for test' bit
#

from="$PWD"
to=$from/install/

#
#   create the target directory
#


echo " "
echo " "
echo "one moment please, creating target directory..."

echo " "
echo "creating $to directory..."
/bin/mkdir $to

#
#   check for directory creation
#

if [ "`/bin/ls -ld $to | cut -c 1`" != "d" ]
then
   echo " "
   echo "error: failed to create $to directory - $current_executable terminated."
   exit 1
fi


#
#   change ownership to allow for modifications
# 

echo " "
echo "setting ownership in $to..."
chown -R $LOGNAME:focussed $to


#
#   change permissions in all directories to allow for modifications
#

echo " "
echo "setting permissions in $to..."
chmod -R 777 $to

#
#   make all executibles
#

cd $from
make imports
if [ $? != 0 ]
then
   echo " "
   echo "error: failed make imports, - $current_executable terminated"
   exit 1
fi

make
if [ $? != 0 ]
then
   echo " "
   echo "error: failed make, - $current_executable terminated"
   exit 1
fi

#
#   Remove any old files in the trima directory...
#

echo " "
echo "cleaning $to..."
/bin/rm -R -f -d $to*


echo " "
echo "copying scripts from $from to $to"
echo " "

/bin/cp -f -v  $from/source/install_trima $to

if [ $? != 0 ]
then
   echo " "
   echo "error: failed cp on $from/install_trima $to - $current_executable terminated"
   exit 1
fi

#
#   archive the source directory in the user's local directory
#

   echo " "
   echo "archiving install"
   cd $from/source
   pax -wv -f $to/install.pax install_boot_image conv_config_40_to_50 install_sysinit \
        install_crc_verification diff awk textto


# setup .mk files for trima builds - in the releases directory
cd $from/install
pwd >../../latest_install_build_dir.mk

echo create_install finished successfully at $(date)
exit 0

