# $Header: //bctQuad3/home/BCT_Development/Trima5.R_PAS/Trima/update/RCS/makefile.vx 1.1 2008/03/12 16:06:16 jheiusb Exp $
#
# Makefile - makefile for the update utility
#
# $Log: makefile.vx $
#

ifeq ($(BUILD_TYPE),CLEAN)
.PHONY: all
all: clean
else
.PHONY: all
all: check_opt_change bin/updateTrima
endif

# ?= won't work in Tornado 2.02 because the version of make is so old
ifeq ($(UPDATEDIR),  )
UPDATEDIR = .
endif

# ------------------------------------------------------------------------------
# Setup MAINDIR and COMDIR. Must use \ (DOS/Windows style) directory separators if they are needed.
# ------------------------------------------------------------------------------
#COMDIR ?= \\bctquad3\HOME\BCT_Development\vxworks\common\common_builds\common_build-6.87_1
# for tornado 2.2/Trima 6.X
COMDIR ?= \\bctquad3\HOME\BCT_Development\Trima5.R\Trima\common_builds\common_build_6.298

# ------------------------------------------------------------------------------
# Define include directories needed for apps built in this directory
# ------------------------------------------------------------------------------
ADDN_INCDIR = -I$(COMDIR)\include -I$(MAINDIR)\trima_common -I$(COMDIR)\os -I$(UPDATEDIR)/../InstallCommon -I$(UPDATEDIR)

# ------------------------------------------------------------------------------
# Define location for Trima libraries
# ------------------------------------------------------------------------------
#LIBDIR = 

#OPTFLAGS := $(OPTFLAGS) -D__COMPILE_FOR_VX_54__
#ADDN_ASFLAGS : $(ADDN_ASFLAGS) -D__COMPILE_FOR_VX_54__
#ADDN_CXXFLAGS := $(ADDN_CXXFLAGS) -D__COMPILE_FOR_VX_54__
#ADDN_CPPFLAGS := $(ADDN_CPPFLAGS) -D__COMPILE_FOR_VX_54__
#ADDN_CCFLAGS := $(ADDN_CCFLAGS) -D__COMPILE_FOR_VX_54__

include $(MAINDIR)/makefile.vxc

# ------------------------------------------------------------------------------
# Definitions required for building update.out
# ------------------------------------------------------------------------------
APP_NAME := update
update_dir  = bin
update_map  = update.map
update_cxx_files = updatetrima.cpp updatetrimaBase.cpp updatetrima5X.cpp updatetrima6X.cpp \
                   updatetrima510.cpp updatetrima514.cpp updatetrima517.cpp updatetrima518.cpp updatetrima520.cpp \
		   updatetrima600.cpp updatetrima610.cpp
update_c_files = discover_hw.c
update_libs = $(COMDIR)/softcrc/lib/libsoftcrc.a $(COMDIR)/zlib/lib/libzlib.a $(MAINDIR)/lib/libtrima_common.a
include $(COMDIR)/makefile.process_app
vpath %.cpp $(UPDATEDIR)/../InstallCommon
vpath %.c $(UPDATEDIR)/../InstallCommon/os
vpath %.h $(UPDATEDIR)/../InstallCommon $(WIND_BASE)

# ------------------------------------------------------------------------------
# Copy update.out to updateTrima (copy instead of move to keep dependency chain intact)
# ------------------------------------------------------------------------------
$(update_dir)/updateTrima:$(update_dir)/$(APP_NAME).out
	cp $< $@

# ------------------------------------------------------------------------------
# Actually build the outfile
# ------------------------------------------------------------------------------
include $(COMDIR)/makefile.build_apps

