#!/bin/ksh
#---------------------------------------------------------------------------
# Copyright (c) 1997, by Cobe BCT, Inc.  All rights reserved
# install_trima - QNX ksh script, written by WTM 10/27/98 
#
#---------------------------------------------------------------------------
#ifdef __USAGE
#%C - install an archived Trima version onto an existing Trima hard drive.
#    
#
#Usage:
#%C 
#
#endif
#---------------------------------------------------------------------------
# Revision History:
# 10/27/98 WTM Creation.
#---------------------------------------------------------------------------
# Move to /d/update...
cd /d/update

me=${0##*/}
startdir=$PWD

echo "*******************************************************"
echo "*******************************************************"
echo "*******************************************************"
echo "*******************************************************"
echo "******                                           ******"
echo "******      STARTING CRC VERIFICATION OF NEW     ******"
echo "******           TRIMA INSTALLATION.             ******"
echo "******                                           ******"
echo "*******************************************************"
echo "*******************************************************"
echo "*******************************************************"
echo "*******************************************************"
#
# Print out the working information.
#
echo "Current directory = ${startdir}"

#
# Ensure that the script is only run in the /d/update directory.
#
if [ $startdir != "/d/update" ] ; then
   echo "$me: MUST BE RUN IN /d/update"
   exit 1
fi

#
echo "Verifying disk CRC..."
/trima/softcrc/machcrc \
     -filelist /trima/softcrc/filelists/trima.files \
     -filelist /trima/softcrc/filelists/focgui.files \
     -filelist /trima/softcrc/filelists/qnx.files \
     -verify /trima/disk.crc 

if [ $? -ne 0 ] ; then
   echo "*******************************************************"
   echo "******         DISK CRC NOT CORRECT              ******"
   echo "******       DO NOT USE THIS INSTALL!!!          ******"
   echo "******     REINSTALL TRIMA BEFORE USE!!!         ******"
   echo "*******************************************************"
else
   echo "Removing update files after successful CRC..."
   rm -rf /d/update/*
   echo "*******************************************************"
   echo "*******************************************************"
   echo "*******************************************************"
   echo "*******************************************************"
   echo "******                                           ******"
   echo "******     DISK CRC VALID, INSTALL COMPLETE.     ******"
   echo "******     REBOOT TO CHECKOUT 4.0 INSTALL.       ******"
   echo "******                                           ******"
   echo "*******************************************************"
   echo "*******************************************************"
   echo "*******************************************************"
   echo "*******************************************************"
   
   
fi

while [ 1 ]
do
  sleep 1
done

exit 0

